# Generated by Django 3.1.12 on 2021-06-04 16:00

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('schema_name', models.CharField(max_length=255)),
                ('schema_iri', models.CharField(max_length=255)),
                ('schema_file', models.FileField(upload_to='schemas/')),
                ('status', models.CharField(choices=[('published', 'published'), ('retired', 'retired')], max_length=10)),
                ('metadata', models.JSONField(blank=True, help_text='auto populated from uploaded file')),
                ('version', models.CharField(help_text='auto populated from other version fields', max_length=5)),
                ('major_version', models.SmallIntegerField()),
                ('minor_version', models.SmallIntegerField()),
                ('revision', models.SmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
