# Generated by Django 3.1.14 on 2022-03-24 18:08

import core.models
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.SlugField(allow_unicode=True, max_length=255)),
                ('description', models.TextField()),
                ('iri', models.SlugField(allow_unicode=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('data_type', models.CharField(max_length=255)),
                ('use', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('required', 'required'), ('optional', 'optional')], max_length=255)),
                ('source', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermSet',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('iri', models.SlugField(allow_unicode=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.SlugField(allow_unicode=True, max_length=255)),
                ('version', models.CharField(max_length=255, validators=[core.models.validate_version])),
                ('status', models.CharField(choices=[('published', 'published'), ('retired', 'retired')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='transformationledger',
            name='source_schema_name',
        ),
        migrations.RemoveField(
            model_name='transformationledger',
            name='source_schema_version',
        ),
        migrations.RemoveField(
            model_name='transformationledger',
            name='target_schema_name',
        ),
        migrations.RemoveField(
            model_name='transformationledger',
            name='target_schema_version',
        ),
    ]
