# Generated by Django 3.1.12 on 2021-06-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemaledger',
            name='version',
            field=models.CharField(help_text='auto populated from other version fields', max_length=6),
        ),
    ]
