# Generated by Django 3.1.14 on 2022-03-24 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20220324_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemaledger',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transformationledger',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transformationledger',
            name='source_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_mapping', to='core.schemaledger'),
        ),
        migrations.AlterField(
            model_name='transformationledger',
            name='target_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_mapping', to='core.schemaledger'),
        ),
        migrations.AddField(
            model_name='termset',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='term',
            name='mapping',
            field=models.ManyToManyField(related_name='_term_mapping_+', to='core.Term'),
        ),
        migrations.AddField(
            model_name='term',
            name='term_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.termset'),
        ),
        migrations.AddField(
            model_name='term',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schemaledger',
            name='term_set',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schema', to='core.termset'),
        ),
        migrations.CreateModel(
            name='ChildTermSet',
            fields=[
                ('termset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.termset')),
                ('parent_term_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.termset')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.termset',),
        ),
    ]
