# Generated by Django 3.1.12 on 2021-06-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210604_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemaledger',
            name='schema_file',
            field=models.FileField(null=True, upload_to='schemas/'),
        ),
    ]
